/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class ReturnLeaseResponse : Message
    {
        public const string RosMessageName = "spot_msgs/srv/ReturnLease";

        public bool success { get; set; }
        public string message { get; set; }

        public ReturnLeaseResponse()
        {
            this.success = false;
            this.message = "";
        }

        public ReturnLeaseResponse(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }
    }
}
#endif
