/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class SetGripperAngleRequest : Message
    {
        public const string RosMessageName = "spot_msgs/srv/SetGripperAngle";

        public float gripper_angle { get; set; }
        // In range [0, 90]

        public SetGripperAngleRequest()
        {
            this.gripper_angle = 0.0f;
        }

        public SetGripperAngleRequest(float gripper_angle)
        {
            this.gripper_angle = gripper_angle;
        }
    }
}
#endif
