/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class SetLocomotionRequest : Message
    {
        public const string RosMessageName = "spot_msgs/srv/SetLocomotion";

        public uint locomotion_mode { get; set; }
        // See https://dev.bostondynamics.com/protos/bosdyn/api/proto_reference.html?highlight=mobilityparams#locomotionhint for details

        public SetLocomotionRequest()
        {
            this.locomotion_mode = 0;
        }

        public SetLocomotionRequest(uint locomotion_mode)
        {
            this.locomotion_mode = locomotion_mode;
        }
    }
}
#endif
