/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class SetLEDBrightnessRequest : Message
    {
        public const string RosMessageName = "spot_msgs/srv/SetLEDBrightness";

        public float brightness { get; set; }
        // In range [0, 1]

        public SetLEDBrightnessRequest()
        {
            this.brightness = 0.0f;
        }

        public SetLEDBrightnessRequest(float brightness)
        {
            this.brightness = brightness;
        }
    }
}
#endif
