/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class SetPtzPositionRequest : Message
    {
        public const string RosMessageName = "spot_msgs/srv/SetPtzPosition";

        //  Angles are in degrees
        public string name { get; set; }
        public float pan { get; set; }
        public float tilt { get; set; }
        public float zoom { get; set; }

        public SetPtzPositionRequest()
        {
            this.name = "";
            this.pan = 0.0f;
            this.tilt = 0.0f;
            this.zoom = 0.0f;
        }

        public SetPtzPositionRequest(string name, float pan, float tilt, float zoom)
        {
            this.name = name;
            this.pan = pan;
            this.tilt = tilt;
            this.zoom = zoom;
        }
    }
}
#endif
