/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class SetStandHeightRequest : Message
    {
        public const string RosMessageName = "spot_msgs/srv/SetStandHeight";

        //  Allows user to request a specific height for Spot to stand relative to default (in m)
        //  -0.15m is crouching and 0.15m is tiptoes
        //  Values outside this range are allowed but Spot will simply go to its min/max
        public float height { get; set; }
        // In range [-0.15, 0.15]

        public SetStandHeightRequest()
        {
            this.height = 0.0f;
        }

        public SetStandHeightRequest(float height)
        {
            this.height = height;
        }
    }
}
#endif
