/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class DescribeParametersResponse : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/DescribeParameters";

        //  A list of the descriptors of all parameters requested in the same order
        //  as they were requested. This list has the same length as the list of
        //  parameters requested.
        public ParameterDescriptor[] descriptors { get; set; }

        public DescribeParametersResponse()
        {
            this.descriptors = new ParameterDescriptor[0];
        }

        public DescribeParametersResponse(ParameterDescriptor[] descriptors)
        {
            this.descriptors = descriptors;
        }
    }
}
#endif
