/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class GetLoggerLevelsRequest : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/GetLoggerLevels";

        //  A list of logger names to get.
        public string[] names { get; set; }

        public GetLoggerLevelsRequest()
        {
            this.names = new string[0];
        }

        public GetLoggerLevelsRequest(string[] names)
        {
            this.names = names;
        }
    }
}
#endif
