/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class GetLoggerLevelsResponse : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/GetLoggerLevels";

        //  List of logger levels which is the same order as the provided names. If a
        //  logger was not yet set, the value will have 'unknown' as the value.
        public LoggerLevel[] levels { get; set; }

        public GetLoggerLevelsResponse()
        {
            this.levels = new LoggerLevel[0];
        }

        public GetLoggerLevelsResponse(LoggerLevel[] levels)
        {
            this.levels = levels;
        }
    }
}
#endif
