/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class GetParametersRequest : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/GetParameters";

        //  TODO(wjwwood): Decide on the rules for grouping, nodes, and parameter "names"
        //  in general, then link to that.
        // 
        //  For more information about parameters and naming rules, see:
        //  https://design.ros2.org/articles/ros_parameters.html
        //  https://github.com/ros2/design/pull/241
        //  A list of parameter names to get.
        public string[] names { get; set; }

        public GetParametersRequest()
        {
            this.names = new string[0];
        }

        public GetParametersRequest(string[] names)
        {
            this.names = names;
        }
    }
}
#endif
