/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class GetParametersResponse : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/GetParameters";

        //  List of values which is the same length and order as the provided names. If a
        //  parameter was not yet set, the value will have PARAMETER_NOT_SET as the
        //  type.
        public ParameterValue[] values { get; set; }

        public GetParametersResponse()
        {
            this.values = new ParameterValue[0];
        }

        public GetParametersResponse(ParameterValue[] values)
        {
            this.values = values;
        }
    }
}
#endif
