/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class GetParameterTypesResponse : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/GetParameterTypes";

        //  List of types which is the same length and order as the provided names.
        // 
        //  The type enum is defined in ParameterType.msg. ParameterType.PARAMETER_NOT_SET
        //  indicates that the parameter is not currently set.
        public byte[] types { get; set; }

        public GetParameterTypesResponse()
        {
            this.types = new byte[0];
        }

        public GetParameterTypesResponse(byte[] types)
        {
            this.types = types;
        }
    }
}
#endif
