/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class ListParametersRequest : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/ListParameters";

        //  Recursively get parameters with unlimited depth.
        public const ulong DEPTH_RECURSIVE = 0;
        //  The list of parameter prefixes to query.
        public string[] prefixes { get; set; }
        //  Relative depth from given prefixes to return.
        // 
        //  Use DEPTH_RECURSIVE to get the recursive parameters and prefixes for each prefix.
        public ulong depth { get; set; }

        public ListParametersRequest()
        {
            this.prefixes = new string[0];
            this.depth = 0;
        }

        public ListParametersRequest(string[] prefixes, ulong depth)
        {
            this.prefixes = prefixes;
            this.depth = depth;
        }
    }
}
#endif
