/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class SetLoggerLevelsResponse : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/SetLoggerLevels";

        //  Indicates whether setting each logger succeeded or not and why.
        public SetLoggerLevelsResult[] results { get; set; }

        public SetLoggerLevelsResponse()
        {
            this.results = new SetLoggerLevelsResult[0];
        }

        public SetLoggerLevelsResponse(SetLoggerLevelsResult[] results)
        {
            this.results = results;
        }
    }
}
#endif
