/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class SetLoggerLevelsRequest : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/SetLoggerLevels";

        //  A list of loggers to set.
        public LoggerLevel[] levels { get; set; }

        public SetLoggerLevelsRequest()
        {
            this.levels = new LoggerLevel[0];
        }

        public SetLoggerLevelsRequest(LoggerLevel[] levels)
        {
            this.levels = levels;
        }
    }
}
#endif
