/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class SetParametersResponse : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/SetParameters";

        //  Indicates whether setting each parameter succeeded or not and why.
        public SetParametersResult[] results { get; set; }

        public SetParametersResponse()
        {
            this.results = new SetParametersResult[0];
        }

        public SetParametersResponse(SetParametersResult[] results)
        {
            this.results = results;
        }
    }
}
#endif
