/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class SetParametersRequest : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/SetParameters";

        //  A list of parameters to set.
        public Parameter[] parameters { get; set; }

        public SetParametersRequest()
        {
            this.parameters = new Parameter[0];
        }

        public SetParametersRequest(Parameter[] parameters)
        {
            this.parameters = parameters;
        }
    }
}
#endif
