/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class SetParametersAtomicallyResponse : Message
    {
        public const string RosMessageName = "rcl_interfaces/srv/SetParametersAtomically";

        //  Indicates whether setting all of the parameters succeeded or not and why.
        public SetParametersResult result { get; set; }

        public SetParametersAtomicallyResponse()
        {
            this.result = new SetParametersResult();
        }

        public SetParametersAtomicallyResponse(SetParametersResult result)
        {
            this.result = result;
        }
    }
}
#endif
