/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class ListParametersResult : Message
    {
        public const string RosMessageName = "rcl_interfaces/msg/ListParametersResult";

        //  The resulting parameters under the given prefixes.
        public string[] names { get; set; }
        //  The resulting prefixes under the given prefixes.
        //  TODO(wjwwood): link to prefix definition and rules.
        public string[] prefixes { get; set; }

        public ListParametersResult()
        {
            this.names = new string[0];
            this.prefixes = new string[0];
        }

        public ListParametersResult(string[] names, string[] prefixes)
        {
            this.names = names;
            this.prefixes = prefixes;
        }
    }
}
#endif
