/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class LoggerLevel : Message
    {
        public const string RosMessageName = "rcl_interfaces/msg/LoggerLevel";

        //  All available logger levels; these correspond to the enum in rcutils/logger.h
        public const byte LOG_LEVEL_UNKNOWN = 0;
        public const byte LOG_LEVEL_DEBUG = 10;
        public const byte LOG_LEVEL_INFO = 20;
        public const byte LOG_LEVEL_WARN = 30;
        public const byte LOG_LEVEL_ERROR = 40;
        public const byte LOG_LEVEL_FATAL = 50;
        //  The logger name.
        public string name { get; set; }
        //  The logger level
        public uint level { get; set; }

        public LoggerLevel()
        {
            this.name = "";
            this.level = 0;
        }

        public LoggerLevel(string name, uint level)
        {
            this.name = name;
            this.level = level;
        }
    }
}
#endif
