/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class ParameterEvent : Message
    {
        public const string RosMessageName = "rcl_interfaces/msg/ParameterEvent";

        //  This message contains a parameter event.
        //  Because the parameter event was an atomic update, a specific parameter name
        //  can only be in one of the three sets.
        //  The time stamp when this parameter event occurred.
        public Time stamp { get; set; }
        //  Fully qualified ROS path to node.
        public string node { get; set; }
        //  New parameters that have been set for this node.
        public Parameter[] new_parameters { get; set; }
        //  Parameters that have been changed during this event.
        public Parameter[] changed_parameters { get; set; }
        //  Parameters that have been deleted during this event.
        public Parameter[] deleted_parameters { get; set; }

        public ParameterEvent()
        {
            this.stamp = new Time();
            this.node = "";
            this.new_parameters = new Parameter[0];
            this.changed_parameters = new Parameter[0];
            this.deleted_parameters = new Parameter[0];
        }

        public ParameterEvent(Time stamp, string node, Parameter[] new_parameters, Parameter[] changed_parameters, Parameter[] deleted_parameters)
        {
            this.stamp = stamp;
            this.node = node;
            this.new_parameters = new_parameters;
            this.changed_parameters = changed_parameters;
            this.deleted_parameters = deleted_parameters;
        }
    }
}
#endif
