/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class Parameter : Message
    {
        public const string RosMessageName = "rcl_interfaces/msg/Parameter";

        //  This is the message to communicate a parameter. It is an open struct with an enum in
        //  the descriptor to select which value is active.
        //  The full name of the parameter.
        public string name { get; set; }
        //  The parameter's value which can be one of several types, see
        //  `ParameterValue.msg` and `ParameterType.msg`.
        public ParameterValue @value { get; set; }

        public Parameter()
        {
            this.name = "";
            this.@value = new ParameterValue();
        }

        public Parameter(string name, ParameterValue @value)
        {
            this.name = name;
            this.@value = @value;
        }
    }
}
#endif
