/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class SetLoggerLevelsResult : Message
    {
        public const string RosMessageName = "rcl_interfaces/msg/SetLoggerLevelsResult";

        //  True when succeed, false when failed.
        public bool successful { get; set; }
        //  Reason why the setting was either successful or a failure.
        public string reason { get; set; }

        public SetLoggerLevelsResult()
        {
            this.successful = false;
            this.reason = "";
        }

        public SetLoggerLevelsResult(bool successful, string reason)
        {
            this.successful = successful;
            this.reason = reason;
        }
    }
}
#endif
