/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.RclInterfaces
{
    public class SetParametersResult : Message
    {
        public const string RosMessageName = "rcl_interfaces/msg/SetParametersResult";

        //  A true value of the same index indicates that the parameter was set
        //  successfully. A false value indicates the change was rejected.
        public bool successful { get; set; }
        //  Reason why the setting was a failure. On success, the contents of this field
        //  are undefined.  This should only be used for logging and user interfaces.
        public string reason { get; set; }

        public SetParametersResult()
        {
            this.successful = false;
            this.reason = "";
        }

        public SetParametersResult(bool successful, string reason)
        {
            this.successful = successful;
            this.reason = reason;
        }
    }
}
#endif
