/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class BatteryStateArray : Message
    {
        public const string RosMessageName = "spot_msgs/msg/BatteryStateArray";

        public BatteryState[] battery_states { get; set; }

        public BatteryStateArray()
        {
            this.battery_states = new BatteryState[0];
        }

        public BatteryStateArray(BatteryState[] battery_states)
        {
            this.battery_states = battery_states;
        }
    }
}
#endif
