/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class BatteryState : Message
    {
        public const string RosMessageName = "spot_msgs/msg/BatteryState";

        //  Status
        public const byte STATUS_UNKNOWN = 0;
        public const byte STATUS_MISSING = 1;
        public const byte STATUS_CHARGING = 2;
        public const byte STATUS_DISCHARGING = 3;
        public const byte STATUS_BOOTING = 4;
        public Header header { get; set; }
        public string identifier { get; set; }
        public double charge_percentage { get; set; }
        public Duration estimated_runtime { get; set; }
        public double current { get; set; }
        public double voltage { get; set; }
        public double[] temperatures { get; set; }
        public byte status { get; set; }

        public BatteryState()
        {
            this.header = new Header();
            this.identifier = "";
            this.charge_percentage = 0.0;
            this.estimated_runtime = new Duration();
            this.current = 0.0;
            this.voltage = 0.0;
            this.temperatures = new double[0];
            this.status = 0;
        }

        public BatteryState(Header header, string identifier, double charge_percentage, Duration estimated_runtime, double current, double voltage, double[] temperatures, byte status)
        {
            this.header = header;
            this.identifier = identifier;
            this.charge_percentage = charge_percentage;
            this.estimated_runtime = estimated_runtime;
            this.current = current;
            this.voltage = voltage;
            this.temperatures = temperatures;
            this.status = status;
        }
    }
}
#endif
