/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class BehaviorFault : Message
    {
        public const string RosMessageName = "spot_msgs/msg/BehaviorFault";

        //  Cause
        public const byte CAUSE_UNKNOWN = 0;
        public const byte CAUSE_FALL = 1;
        public const byte CAUSE_HARDWARE = 2;
        //  Status
        public const byte STATUS_UNKNOWN = 0;
        public const byte STATUS_CLEARABLE = 1;
        public const byte STATUS_UNCLEARABLE = 2;
        public Header header { get; set; }
        public uint behavior_fault_id { get; set; }
        public byte cause { get; set; }
        public byte status { get; set; }

        public BehaviorFault()
        {
            this.header = new Header();
            this.behavior_fault_id = 0;
            this.cause = 0;
            this.status = 0;
        }

        public BehaviorFault(Header header, uint behavior_fault_id, byte cause, byte status)
        {
            this.header = header;
            this.behavior_fault_id = behavior_fault_id;
            this.cause = cause;
            this.status = status;
        }
    }
}
#endif
