/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class EStopStateArray : Message
    {
        public const string RosMessageName = "spot_msgs/msg/EStopStateArray";

        public EStopState[] estop_states { get; set; }

        public EStopStateArray()
        {
            this.estop_states = new EStopState[0];
        }

        public EStopStateArray(EStopState[] estop_states)
        {
            this.estop_states = estop_states;
        }
    }
}
#endif
