/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class EStopState : Message
    {
        public const string RosMessageName = "spot_msgs/msg/EStopState";

        //  Type
        public const byte TYPE_UNKNOWN = 0;
        public const byte TYPE_HARDWARE = 1;
        public const byte TYPE_SOFTWARE = 2;
        //  State
        public const byte STATE_UNKNOWN = 0;
        public const byte STATE_ESTOPPED = 1;
        public const byte STATE_NOT_ESTOPPED = 2;
        public Header header { get; set; }
        public string name { get; set; }
        public byte type { get; set; }
        public byte state { get; set; }
        public string state_description { get; set; }

        public EStopState()
        {
            this.header = new Header();
            this.name = "";
            this.type = 0;
            this.state = 0;
            this.state_description = "";
        }

        public EStopState(Header header, string name, byte type, byte state, string state_description)
        {
            this.header = header;
            this.name = name;
            this.type = type;
            this.state = state;
            this.state_description = state_description;
        }
    }
}
#endif
