/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class Feedback : Message
    {
        public const string RosMessageName = "spot_msgs/msg/Feedback";

        public bool standing { get; set; }
        public bool sitting { get; set; }
        public bool moving { get; set; }
        public string serial_number { get; set; }
        public string species { get; set; }
        public string version { get; set; }
        public string nickname { get; set; }
        public string computer_serial_number { get; set; }

        public Feedback()
        {
            this.standing = false;
            this.sitting = false;
            this.moving = false;
            this.serial_number = "";
            this.species = "";
            this.version = "";
            this.nickname = "";
            this.computer_serial_number = "";
        }

        public Feedback(bool standing, bool sitting, bool moving, string serial_number, string species, string version, string nickname, string computer_serial_number)
        {
            this.standing = standing;
            this.sitting = sitting;
            this.moving = moving;
            this.serial_number = serial_number;
            this.species = species;
            this.version = version;
            this.nickname = nickname;
            this.computer_serial_number = computer_serial_number;
        }
    }
}
#endif
