/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class FootState : Message
    {
        public const string RosMessageName = "spot_msgs/msg/FootState";

        //  Contact
        public const byte CONTACT_UNKNOWN = 0;
        public const byte CONTACT_MADE = 1;
        public const byte CONTACT_LOST = 2;
        public Point foot_position_rt_body { get; set; }
        public byte contact { get; set; }

        public FootState()
        {
            this.foot_position_rt_body = new Point();
            this.contact = 0;
        }

        public FootState(Point foot_position_rt_body, byte contact)
        {
            this.foot_position_rt_body = foot_position_rt_body;
            this.contact = contact;
        }
    }
}
#endif
