/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class JointCommand : Message
    {
        public const string RosMessageName = "spot_msgs/msg/JointCommand";

        //  list of the joint names to control
        public string[] name { get; set; }
        //  desired position commands for each joint in rad
        public double[] position { get; set; }
        //  desired velocity commands for each joint in rad/s
        public double[] velocity { get; set; }
        //  desired effort commands for each joint in Nm
        public double[] effort { get; set; }
        //  desired k_q_p commands for each joint in Nm/rad
        public double[] k_q_p { get; set; }
        //  desired k_qd_p command for each joint in Nms/rad
        public double[] k_qd_p { get; set; }

        public JointCommand()
        {
            this.name = new string[0];
            this.position = new double[0];
            this.velocity = new double[0];
            this.effort = new double[0];
            this.k_q_p = new double[0];
            this.k_qd_p = new double[0];
        }

        public JointCommand(string[] name, double[] position, double[] velocity, double[] effort, double[] k_q_p, double[] k_qd_p)
        {
            this.name = name;
            this.position = position;
            this.velocity = velocity;
            this.effort = effort;
            this.k_q_p = k_q_p;
            this.k_qd_p = k_qd_p;
        }
    }
}
#endif
