/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class LeaseResource : Message
    {
        public const string RosMessageName = "spot_msgs/msg/LeaseResource";

        public string resource { get; set; }
        public Lease lease { get; set; }
        public LeaseOwner lease_owner { get; set; }

        public LeaseResource()
        {
            this.resource = "";
            this.lease = new Lease();
            this.lease_owner = new LeaseOwner();
        }

        public LeaseResource(string resource, Lease lease, LeaseOwner lease_owner)
        {
            this.resource = resource;
            this.lease = lease;
            this.lease_owner = lease_owner;
        }
    }
}
#endif
