/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class LeaseOwner : Message
    {
        public const string RosMessageName = "spot_msgs/msg/LeaseOwner";

        public string client_name { get; set; }
        public string user_name { get; set; }

        public LeaseOwner()
        {
            this.client_name = "";
            this.user_name = "";
        }

        public LeaseOwner(string client_name, string user_name)
        {
            this.client_name = client_name;
            this.user_name = user_name;
        }
    }
}
#endif
