/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class LeaseArray : Message
    {
        public const string RosMessageName = "spot_msgs/msg/LeaseArray";

        public LeaseResource[] resources { get; set; }

        public LeaseArray()
        {
            this.resources = new LeaseResource[0];
        }

        public LeaseArray(LeaseResource[] resources)
        {
            this.resources = resources;
        }
    }
}
#endif
