/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class Lease : Message
    {
        public const string RosMessageName = "spot_msgs/msg/Lease";

        public string resource { get; set; }
        public string epoch { get; set; }
        public uint[] sequence { get; set; }

        public Lease()
        {
            this.resource = "";
            this.epoch = "";
            this.sequence = new uint[0];
        }

        public Lease(string resource, string epoch, uint[] sequence)
        {
            this.resource = resource;
            this.epoch = epoch;
            this.sequence = sequence;
        }
    }
}
#endif
