/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class Metrics : Message
    {
        public const string RosMessageName = "spot_msgs/msg/Metrics";

        public Header header { get; set; }
        public float distance { get; set; }
        public int gait_cycles { get; set; }
        public Duration time_moving { get; set; }
        public Duration electric_power { get; set; }

        public Metrics()
        {
            this.header = new Header();
            this.distance = 0.0f;
            this.gait_cycles = 0;
            this.time_moving = new Duration();
            this.electric_power = new Duration();
        }

        public Metrics(Header header, float distance, int gait_cycles, Duration time_moving, Duration electric_power)
        {
            this.header = header;
            this.distance = distance;
            this.gait_cycles = gait_cycles;
            this.time_moving = time_moving;
            this.electric_power = electric_power;
        }
    }
}
#endif
