/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class MobilityParams : Message
    {
        public const string RosMessageName = "spot_msgs/msg/MobilityParams";

        public Pose body_control { get; set; }
        public uint locomotion_hint { get; set; }
        public uint stairs_mode { get; set; }

        public MobilityParams()
        {
            this.body_control = new Pose();
            this.locomotion_hint = 0;
            this.stairs_mode = 0;
        }

        public MobilityParams(Pose body_control, uint locomotion_hint, uint stairs_mode)
        {
            this.body_control = body_control;
            this.locomotion_hint = locomotion_hint;
            this.stairs_mode = stairs_mode;
        }
    }
}
#endif
