/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class PowerState : Message
    {
        public const string RosMessageName = "spot_msgs/msg/PowerState";

        //  MotorPowerState
        public const byte STATE_UNKNOWN = 0;
        public const byte STATE_OFF = 1;
        public const byte STATE_ON = 2;
        public const byte STATE_POWERING_ON = 3;
        public const byte STATE_POWERING_OFF = 4;
        public const byte STATE_ERROR = 5;
        //  ShorePowerState
        public const byte STATE_UNKNOWN_SHORE_POWER = 0;
        public const byte STATE_ON_SHORE_POWER = 1;
        public const byte STATE_OFF_SHORE_POWER = 2;
        public Header header { get; set; }
        public byte motor_power_state { get; set; }
        public byte shore_power_state { get; set; }
        public double locomotion_charge_percentage { get; set; }
        public Duration locomotion_estimated_runtime { get; set; }

        public PowerState()
        {
            this.header = new Header();
            this.motor_power_state = 0;
            this.shore_power_state = 0;
            this.locomotion_charge_percentage = 0.0;
            this.locomotion_estimated_runtime = new Duration();
        }

        public PowerState(Header header, byte motor_power_state, byte shore_power_state, double locomotion_charge_percentage, Duration locomotion_estimated_runtime)
        {
            this.header = header;
            this.motor_power_state = motor_power_state;
            this.shore_power_state = shore_power_state;
            this.locomotion_charge_percentage = locomotion_charge_percentage;
            this.locomotion_estimated_runtime = locomotion_estimated_runtime;
        }
    }
}
#endif
