/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Spot
{
    public class WiFiState : Message
    {
        public const string RosMessageName = "spot_msgs/msg/WiFiState";

        //  Mode
        public const byte MODE_UNKNOWN = 0;
        public const byte MODE_ACCESS_POINT = 1;
        public const byte MODE_CLIENT = 2;
        public byte current_mode { get; set; }
        public string essid { get; set; }

        public WiFiState()
        {
            this.current_mode = 0;
            this.essid = "";
        }

        public WiFiState(byte current_mode, string essid)
        {
            this.current_mode = current_mode;
            this.essid = essid;
        }
    }
}
#endif
